project:
  type: website
  output-dir: ../docs

website:
  title: "Toward an Open Science Ecosystem in Neuroimaging"
  navbar:
    left:
      - href: https://github.com/poldrack/talks-OpenScienceEcosystem
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

